import 'package:bank_dashboard/ui/shared/edge_insect.dart';
import 'package:flutter/material.dart';

class Datatable extends StatefulWidget {
  const Datatable({Key? key}) : super(key: key);

  @override
  State<Datatable> createState() => _DatatableState();
}

class _DatatableState extends State<Datatable> {
  @override
  Widget build(BuildContext context) {
    return datatablewidget();
  }
}

class datatablewidget extends StatelessWidget {
  const datatablewidget({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(scrollDirection: Axis.horizontal,
      child
          : Stack(
            children: [Container(
        color: Colors.grey,
            child: DataTable(
              columnSpacing:defaultPadding,
              columns: const [
                DataColumn(
                  label: Text("Area"),
                ),
                DataColumn(
                  label: Text("Birthday"),
                ),
                DataColumn(
                  label: Text("CID"),
                ),
                DataColumn(
                  label: Text("Centername"),
                ),
                DataColumn(
                  label: Text("Contact"),
                ),
                DataColumn(
                  label: Text("Flag"),
                ),
                DataColumn(
                  label: Text("Lenghtofmembership"),
                ),
                DataColumn(
                  label: Text("Membername"),
                ),
                DataColumn(
                  label: Text("Newbranchcode"),
                ),
                DataColumn(
                  label: Text("Newcid"),
                ),
                DataColumn(
                  label: Text("Recognizeddate"),
                ),
                DataColumn(
                  label: Text("Dateuploaded"),
                ),
                DataColumn(
                  label: Text("Unit"),
                ),
                DataColumn(
                  label: Text("Spousename"),
                ),
                DataColumn(
                  label: Text("Address"),
                ),
                DataColumn(
                  label: Text("Meetingday"),
                ),
              ], rows: const [
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),
              DataRow(cells: [
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
                DataCell(Text('text'),),
              ]),


            ],

            ),
        ),
          ]
      ),
    );
  }
}
